### ISSUE TITLE
Server-side rendering issue

### ISSUE THREAD

**Issue by scf4** [tvkhoa/react-tippy#15]
I'm getting `ReferenceError: Element is not defined`:
```
node_modules/react-tippy/dist/react-tippy.js:737
var matches = exports.matches = Element.prototype.matches || Element.prototype.matchesSelector || Element.prototype.webkitMatchesSelector || Element.prototype.mozMatchesSelector || Element.prototype.msMatchesSelector || function (s) {
```

Thanks!

**Comment by mandriv** [comment]
@scf4 
I am getting this error out of blue again in 1.2.2., no issues with 1.2.1
```
Element is not defined
ReferenceError: Element is not defined
    at Object.defineProperty.value (src/Tooltip/js/utils/matches.js:10:2)
    at __webpack_require__ (webpack:/webpack/bootstrap 7ee337d31cbb41abd788:19:0)
    at Object.defineProperty.value (src/Tooltip/js/utils/closest.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7ee337d31cbb41abd788:19:0)
    at Object.defineProperty.value (src/Tooltip/js/core/bindEventListeners.js:5:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7ee337d31cbb41abd788:19:0)
    at Object.defineProperty.value (src/Tooltip/js/core/init.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7ee337d31cbb41abd788:19:0)
    at Object.defineProperty.value (src/Tooltip/js/tippy.js:9:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7ee337d31cbb41abd788:19:0)
    at Object.defineProperty.value (src/Tooltip/component.js:2:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7ee337d31cbb41abd788:19:0)
    at Object.defineProperty.value (src/Tooltip/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 7ee337d31cbb41abd788:19:0)
    at Object.defineProperty.value (webpack:/webpack/bootstrap 7ee337d31cbb41abd788:65:0)
    at /xxx/xxx/xxx/xxx/xxx/node_modules/react-tippy/dist/react-tippy.js:79:10

**Comment by timpeti** [comment]
Same here

**Comment by LauraBeatris** [comment]
Same here

**Comment by scf4** [comment]
on the latest version?

**Comment by LauraBeatris** [comment]
Yup! With ``react-static``

![Screen Shot 2020-07-19 at 09 06 47](https://user-images.githubusercontent.com/48022589/87874309-35ee1580-c99f-11ea-8a0c-b1508945d02c.png)

**Comment by scf4** [comment]
Weird, I'm not having any problems. Reopen another issue @LauraBeatris

**Comment by vsharma918** [comment]
I am also getting same issue while SSR.

**Comment by LauraBeatris** [comment]
@scf4 @vsharma918 I don't if it depends of the version of the React Static or the way the routes are being exported during the build process.  

But the way that I got to fix it was to create a wrapper and conditionally import the library: 

```
import React from "react";

import isSSR from "../../constants/isSSR";

/*
  SSR issue when rendering UI components that rely on document
  Refer to: https://github.com/react-static/react-static/issues/288#issuecomment-356356652
*/
let Tooltip;

if (!isSSR) {
  // eslint-disable-next-line global-require
  Tooltip = require("react-tippy").default;
}

const TooltipWrapper = (props) => {
  if (!Tooltip) {
    return null;
  }

  return (
    <Tooltip {...props} />
  );
};

export default TooltipWrapper;

```
